---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

# Install ansible
addons:
#  ssh_known_hosts: 
#    - localhost
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - ansible-playbook tests/test.yml --syntax-check
  - ansible-playbook tests/test.yml -C
  - ansible-playbook tests/test.yml 

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
